package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1



/**
 * AvaliacaoSupermercado generated by hbm2java
 */
public class AvaliacaoSupermercado  implements java.io.Serializable {


     private int id;
     private Supermercado supermercado;
     private Usuario usuario;
     private short estrelas;
     private String comentario;

    public AvaliacaoSupermercado() {
    }

	
    public AvaliacaoSupermercado(Supermercado supermercado, Usuario usuario, short estrelas) {
        this.supermercado = supermercado;
        this.usuario = usuario;
        this.estrelas = estrelas;
    }
    public AvaliacaoSupermercado(Supermercado supermercado, Usuario usuario, short estrelas, String comentario) {
       this.supermercado = supermercado;
       this.usuario = usuario;
       this.estrelas = estrelas;
       this.comentario = comentario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Supermercado getSupermercado() {
        return this.supermercado;
    }
    
    public void setSupermercado(Supermercado supermercado) {
        this.supermercado = supermercado;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public short getEstrelas() {
        return this.estrelas;
    }
    
    public void setEstrelas(short estrelas) {
        this.estrelas = estrelas;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


