package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1


/**
 * AvaliacaoProduto generated by hbm2java
 */
public class AvaliacaoProduto implements java.io.Serializable {

    private int id;
    private Produto produto;
    private Usuario usuario;
    private short estrelas;
    private String comentario;

    public AvaliacaoProduto() {
    }

    public AvaliacaoProduto(int id, Produto produto, Usuario usuario, short estrelas) {
        this.id = id;
        this.produto = produto;
        this.usuario = usuario;
        this.estrelas = estrelas;
    }

    public AvaliacaoProduto(int id, Produto produto, Usuario usuario, short estrelas, String comentario) {
        this.id = id;
        this.produto = produto;
        this.usuario = usuario;
        this.estrelas = estrelas;
        this.comentario = comentario;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Produto getProduto() {
        return this.produto;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public short getEstrelas() {
        return this.estrelas;
    }

    public void setEstrelas(short estrelas) {
        this.estrelas = estrelas;
    }

    public String getComentario() {
        return this.comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

}
