package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * CartaoCredito generated by hbm2java
 */
public class CartaoCredito implements java.io.Serializable {

    private int id;
    private Usuario usuario;
    private String numeroCartao;
    private Date validadeDe;
    private Date validadeAte;
    private String nomeTitular;
    private String codSeguranca;
    private short tipo;

    public CartaoCredito() {
    }

    public CartaoCredito(String numeroCartao, Date validadeDe, Date validadeAte, String nomeTitular, String codSeguranca, short tipo) {
        this.numeroCartao = numeroCartao;
        this.validadeDe = validadeDe;
        this.validadeAte = validadeAte;
        this.nomeTitular = nomeTitular;
        this.codSeguranca = codSeguranca;
        this.tipo = tipo;
    }

    public CartaoCredito(Usuario usuario, String numeroCartao, Date validadeDe, Date validadeAte, String nomeTitular, String codSeguranca, short tipo) {
        this.usuario = usuario;
        this.numeroCartao = numeroCartao;
        this.validadeDe = validadeDe;
        this.validadeAte = validadeAte;
        this.nomeTitular = nomeTitular;
        this.codSeguranca = codSeguranca;
        this.tipo = tipo;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getNumeroCartao() {
        return this.numeroCartao;
    }

    public void setNumeroCartao(String numeroCartao) {
        this.numeroCartao = numeroCartao;
    }

    public Date getValidadeDe() {
        return this.validadeDe;
    }

    public void setValidadeDe(Date validadeDe) {
        this.validadeDe = validadeDe;
    }

    public Date getValidadeAte() {
        return this.validadeAte;
    }

    public void setValidadeAte(Date validadeAte) {
        this.validadeAte = validadeAte;
    }

    public String getNomeTitular() {
        return this.nomeTitular;
    }

    public void setNomeTitular(String nomeTitular) {
        this.nomeTitular = nomeTitular;
    }

    public String getCodSeguranca() {
        return this.codSeguranca;
    }

    public void setCodSeguranca(String codSeguranca) {
        this.codSeguranca = codSeguranca;
    }

    public short getTipo() {
        return this.tipo;
    }

    public void setTipo(short tipo) {
        this.tipo = tipo;
    }

}
