package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1



/**
 * CompraTemProduto generated by hbm2java
 */
public class CompraTemProduto  implements java.io.Serializable {


     private int id;
     private Compra compra;
     private Produto produto;
     private short quantidade;

    public CompraTemProduto() {
    }

    public CompraTemProduto(int id, Compra compra, Produto produto, short quantidade) {
       this.id = id;
       this.compra = compra;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public short getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(short quantidade) {
        this.quantidade = quantidade;
    }




}


