package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1



/**
 * Entrega generated by hbm2java
 */
public class Entrega  implements java.io.Serializable {


     private int id;
     private Compra compra;
     private Endereco endereco;
     private byte status;

    public Entrega() {
    }

    public Entrega(Compra compra, Endereco endereco, byte status) {
       this.compra = compra;
       this.endereco = endereco;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


