package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private int id;
     private String nome;

    public Marca() {
    }

	
    public Marca(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Marca(int id, String nome, Set produtos) {
       this.id = id;
       this.nome = nome;
   
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
   


}


