package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int id;
     private Marca marca;
     private Subcategoria subcategoria;
     private String nome;
     private String ean13;
     private String descricao;
     private byte[] imagem;
     private String info;
     private Set supermercadoTemProdutos = new HashSet(0);
     private Set avaliacaoProdutos = new HashSet(0);
     private Set compraTemProdutos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(Marca marca, Subcategoria subcategoria, String nome, String ean13, String descricao, byte[] imagem) {
        this.marca = marca;
        this.subcategoria = subcategoria;
        this.nome = nome;
        this.ean13 = ean13;
        this.descricao = descricao;
        this.imagem = imagem;
    }
    public Produto(Marca marca, Subcategoria subcategoria, String nome, String ean13, String descricao, byte[] imagem, String info, Set supermercadoTemProdutos, Set avaliacaoProdutos, Set compraTemProdutos) {
       this.marca = marca;
       this.subcategoria = subcategoria;
       this.nome = nome;
       this.ean13 = ean13;
       this.descricao = descricao;
       this.imagem = imagem;
       this.info = info;
       this.supermercadoTemProdutos = supermercadoTemProdutos;
       this.avaliacaoProdutos = avaliacaoProdutos;
       this.compraTemProdutos = compraTemProdutos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEan13() {
        return this.ean13;
    }
    
    public void setEan13(String ean13) {
        this.ean13 = ean13;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public byte[] getImagem() {
        return this.imagem;
    }
    
    public void setImagem(byte[] imagem) {
        this.imagem = imagem;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Set getSupermercadoTemProdutos() {
        return this.supermercadoTemProdutos;
    }
    
    public void setSupermercadoTemProdutos(Set supermercadoTemProdutos) {
        this.supermercadoTemProdutos = supermercadoTemProdutos;
    }
    public Set getAvaliacaoProdutos() {
        return this.avaliacaoProdutos;
    }
    
    public void setAvaliacaoProdutos(Set avaliacaoProdutos) {
        this.avaliacaoProdutos = avaliacaoProdutos;
    }
    public Set getCompraTemProdutos() {
        return this.compraTemProdutos;
    }
    
    public void setCompraTemProdutos(Set compraTemProdutos) {
        this.compraTemProdutos = compraTemProdutos;
    }




}


