package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private int id;
     private Categoria categoria;
     private String nome;
     private Set produtos = new HashSet(0);

    public Subcategoria() {
    }

	
    public Subcategoria(Categoria categoria, String nome) {
        this.categoria = categoria;
        this.nome = nome;
    }
    public Subcategoria(Categoria categoria, String nome, Set produtos) {
       this.categoria = categoria;
       this.nome = nome;
       this.produtos = produtos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


