package br.pucminas.supermercado.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private int id;
     private Categoria categoria;
     private String nome;
    

    public Subcategoria() {
    }

	
    public Subcategoria(Categoria categoria, String nome) {
        this.categoria = categoria;
        this.nome = nome;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
  
}


