package br.pucminas.supermercado.model;
// Generated 17/08/2017 22:19:53 by Hibernate Tools 4.3.1



/**
 * SupermercadoTemProduto generated by hbm2java
 */
public class SupermercadoTemProduto  implements java.io.Serializable {


     private int id;
     private Produto produto;
     private Supermercado supermercado;
     private byte disponibilidade;
     private float preco;

    public SupermercadoTemProduto() {
    }

    public SupermercadoTemProduto(Produto produto, Supermercado supermercado, byte disponibilidade, float preco) {
       this.produto = produto;
       this.supermercado = supermercado;
       this.disponibilidade = disponibilidade;
       this.preco = preco;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Supermercado getSupermercado() {
        return this.supermercado;
    }
    
    public void setSupermercado(Supermercado supermercado) {
        this.supermercado = supermercado;
    }
    public byte getDisponibilidade() {
        return this.disponibilidade;
    }
    
    public void setDisponibilidade(byte disponibilidade) {
        this.disponibilidade = disponibilidade;
    }
    public float getPreco() {
        return this.preco;
    }
    
    public void setPreco(float preco) {
        this.preco = preco;
    }




}


