package br.pucminas.supermercado.model;

import java.util.HashSet;
import java.util.InputMismatchException;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public final class Usuario implements java.io.Serializable {

    private int id;        
    private String nome;//128
    private String cpf; //11
    private String telefone;//14
    private String email;//128
    private String senha;//20
    private Endereco endereco;
//    private Set cartaoCreditos = new HashSet(0);
//    private Set compras = new HashSet(0);
//    private Set avaliacaoProdutos = new HashSet(0);
//    private Set avaliacaoSupermercados = new HashSet(0);

    public Usuario() {
    }

    public Usuario(Endereco endereco, String cpf, String nome, String telefone, String email, String senha) {
        
        setCpf(cpf);
        setNome(nome);
        setTelefone(telefone);
        setEmail(email);
        setSenha(senha);
        setEndereco(endereco);
    }


    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;        
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {        
        this.nome = nome;
    }

    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    

    @Override
    public String toString() {
        return id + " " + nome + " " + email + " " + " " + telefone;
    }

    
    

}
